apiVersion: v1
kind: ConfigMap
metadata:
  name: grampsweb
data:
  GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb-redis:6379/0"
  GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb-redis:6379/0"
  GRAMPSWEB_RATELIMIT_STORAGE_URI: "redis://grampsweb-redis:6379/1"
  GRAMPSWEB_TREE: "tree"
  GRAMPSWEB_POSTGRES_USER: [db_user_name]
  GRAMPSWEB_DATABASE_HOST: [host]
  GRAMPSWEB_DATABASE_PORT: [port]
  GRAMPSWEB_NEW_DB_BACKEND: "postgresql"
  GRAMPSWEB_DATABASE_BACKEND: "postgresql"